### ISSUE TITLE
MsExperiment devel call

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/MsExperiment#13]
Tentative agenda:

- Presentation of the current state of the package
- Should we support list of data items (see [here](https://github.com/rformassspectrometry/MsExperiment/issues/1#issuecomment-498615699))
- I don't think we need to support subsetting or data processing operations on `MsExperiment` (see [here](https://github.com/rformassspectrometry/MsExperiment/issues/2)) - the main aim is data management and processing should be performed independently on the data objects.
- Should we support an `otherData` list slot for other non-standard data? Or rather promote the creation of new sub-classes? Probably both. An `otherData` slot could be used for PSMs (I don't think a dedicated slot is ideal), and possibly for additional spectra/chromatograms (see second bullet point above).
- Matching between data using a primary key (see how currently joining of raw and id data works). PK to be defined by user and checked for. 
- Submission to Bioconductor.

Please add any other discussion points to this issue.  

Ping @jorainer @sgibb @ococrook 

Call will be help on **Thu 22 April** at **9 am (UK)/10 (EU)** on https://meet.jit.si/RforMassSpectrometry.

**Comment by ococrook** [comment]
Looks like a good agenda. Generally not free tuesday or Friday, late afternoon most other times are good

**Comment by lgatto** [comment]
Short summary from this morning's call:

- I added the `otherData` slot
- I renamed `colData` to `sampleData` with getter/setter and added a short example in the vignette.
- Discussion on subsetting going on (see #17)
