### ISSUE TITLE
Use case: manage experiment and sample associations

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/MsExperiment#17]
I try to describe a common use case I could envision on an `MsExperiment` object (note that this is actually very much like the `MSnExp`/`OnDiskMSnExp` classes are working).

- Experiment consists of several samples (potentially in different conditions) measured in different runs). This can be defined with e.g. the `data.frame` below:

```r
sdata <- data.frame(
    sample = c("a_1", "a_2", "qc_1", "b_1", "b_2", "qc_2"),
    individual = c("a", "a", "pool", "b", "b", "pool"),
    timepoint = c(1, 2, NA, 1, 2, NA))
```

- Each sample would now be measured with an LC-MS setup and we get for each sample an mzML file.

```r
mzml <- c("qc_1.mzML", "a_1.mzML", "b_2.mzML", "qc_2.mzML", "a_2.mzML", "b_1.mzML")
```

- I would then load the data into an `MsExperiment`, the sample annotations, the file names and load also the spectra from the mzML. Let's call this object `mse`.
- first thing I would need to do is to **reorder** the samples and files (Spectra) according to the sequence in which they were measured (that's important because we observe signal drifts that are related to when a sample was measured in a series of measurements).
- I would then create base peak chromatograms (or total ion chromatograms) to evaluate whether the total signal eluting from the LC is comparable across the samples or if we have potentially failed injections.
- Eventually I would need to remove one or more samples from the experiment.

So, subsetting **by sample** is a key thing in any of my workflows. Thus I would need support for an `[, j]` operation that allows also an arbitrary re-ordering of the samples within the object.

In the next steps I would run, with `xcms` peak detection, alignment and correspondence on a per-file basis. To store the results from that I can create my own object extending `MsExperiment`. Ultimately, however, the *feature matrix* I get from the correspondence analysis would be again ~ compatible with the `QFeatures`.

**Comment by jorainer** [comment]
I could work on a `LinkedMsExperiment` object that extends `MsExperiment` and allows to *link* between files and samples. I would suggest that, if you @lgatto also want to try to define such functionality, to implement another object extending `MsExperiment` instead of changing/implementing that directly `MsExperiment`. That way we could compare implementations and approaches  - also, any of these developments won't influence the `MsExperiment`.

**Comment by lgatto** [comment]
Could you please define what you mean by *link*, because having the same filenames in the `sampleData`, `MsExperimentFiles` and `spectra(.)$dataOrigin` is a type of link. I am very wary of overly complexifying something that can be easily handled by documented. 

Another possibility is to have a function that checks any of these links, so that it can be used only when needed (see for examples [existMsExperimentFiles](https://rformassspectrometry.github.io/MsExperiment/reference/MsExperimentFiles.html)).

**Comment by jorainer** [comment]
I would like to evaluate what works better as *link* - as you said, this could be simply be the file names or even a seprate `data.frame` with indices/primary keys e.g matching each spectrum in `@spectra` with a row in `sampleData`. Some thoughts on that: file names would be nice because they are already there, but then IMHO we need to have a *link* that specifies which `spectraVariable` (default `$dataOrigin`) maps/links to which column in `sampleData` and to which list element in `MsExperimentFiles`.

I agree that overly complexifying is not good - that's why I thought of first creating a separate object to see how this could be implemented in an (easy) way that still fits my needs.

**Comment by lgatto** [comment]
Sure, let's explore. We can also discuss further - it's sometimes easier/faster than over an issue.

Note that the files in `MsExperimentFiles` and `$dataOrigin` would match by default if the user first sets the former and then generates the spectra using the experiment files. That would already be a working link by simply doing things in the right order and could be checked (but not enforced) with a simple function.

**Comment by jorainer** [comment]
Before discussing I would like to play around with actual code - it's easier for me to understand what's going on or what's to complicated.

I like the idea of having a *loosly connected* vs a *linked* `MsExperiment`. I would also not enforce the links, but just allow e.g. subsetting by sample if a link is present.

**Comment by jorainer** [comment]
A typical workflow for untargeted LC-MS(/MS) would be:

```r
## Define a data frame with the sample description for an experiment
sampledf <- data.frame(
    id = c("a", "b", "c"),
    mzml = c("a.mzML", "b.mzML", "c.mzML"),
    group = c(1, 2, 1),
    time = c(8, 2, 4)
)

## Create an `MsExperiment` for that experimental setup
mse <- MsExperiment(sampleData = sampledf)
```

Add measured files. Defining both the raw mzML files as well as an SQLite file with (all) the data for an `MsBackendSQL` backend.

```r
## add measured files.
msfls <- MsExperimentFiles(
    original_files = paste0("/data/massspec/", sampledf$mzml),
    sql_backend = "~/exp1.sqlite")
experimentFiles(mse) <- msfls

## read spectra from SQL backend
spectra(mse) <- Spectra(experimentFiles(mse)$sql_backend)
```

Up to this point we have only a *loose* relationship between experiment files, samples and spectra. To simplify some processing steps (like subsetting etc) I would however prefer to also allow *explicit* relationships (links) between samples and data. A `linkSampleData` function could be used to add such links:

```r
## Different options to link between entities within an MsExperiment:
##
## establish explicit links between files and samples:
## original raw files and samples: link between each sample and its original file 
## in @experimentFiles 
mse <- linkSampleData(mse, with = "experimentFiles.original_files",
                      toIndex = 1:3)
## optionally link also the backend file: all samples link to that one file.
mse <- linkSampleData(mse, with = "experimentFiles.sql_backend", toIndex = 1)

## Link the individual spectra to samples.
mse <- linkSampleData(mse, with = "spectra",
                      from = sampleData(mse)$original_files,
                      to = basename(spectra(mse)$dataOrigin))

## We could also support SQL join like links (with <slot>.<column name>)
mse <- linkSampleData(mse, with = "spectra.dataOrigin = sampleData.original_files")
```

With this links added `mse` *knows* which files and spectra belong to which samples, with the need for the user to specify that once (some links could also be automatically added with some higher level reading/importing functions). The typical workflow to process the data from here could be to first calculate base peak chromatograms of the data and to visualize that (check if the chromatograms between samples are comparable). The explicit links simplify these tasks without the user needing to specify that relationship with each operation.

```r
## calculate/extract base peak chromatogram per sample
chr <- chromatogram(mse)
## plot the chromatograms labeling the chromatograms by sample group
plot(chr, col = mse$group)
```

Also, (coherent) subsetting could be done in typical R fashion

```r
## subsetting will subset:
## - sampleData
## - any other slot for which a link exists
##
## Example use cases:
## Re-order experiment by time
mse <- mse[, order(mse$time)]

## extract samples/files from one group (or exclude QC samples etc)
group_1 <- mse[, mse$group == 1]
```

And I could use this right away for `xcms`-based preprocessing:

```r
## xcms processing
xcmse <- findChromPeaks(mse, param = CentWaveParam)
## splits spectra by sample, performs peak detection returns
## identified peak matrix (list of matrices) and stores them to `@otherData`
## adding also a link of each matrix to each sample.
```

While I agree that this adds more complexity to `MsExperiment` I think it can be helpful, especially for the end user. Loosing the link between sample description and data is in my experience one of the main sources of errors and confutions. Without the links the `MsExperiment` feels more like an unordered `list` of data.

Happy for feedback @lgatto and also @sgibb (if you find time for it)

**Comment by lgatto** [comment]
This looks very nice indeed. I like the implementation with a function that creates the links! 

Curious to look at the code (if it exists) and try it out.

**Comment by jorainer** [comment]
Funny, I thought you will not like the approach :) it's pretty simple - internally, each link will be represented as integer `matrix` with the indices of the mapped entities.

It's not fully implemented yet. I'll work on it and make then a PR.

**Comment by lgatto** [comment]
Not like it?!? I **love** it!

**Comment by jorainer** [comment]
Before jumping on the implementation of the subsetting operation I would like to explain what I think it should do and support:

Subsetting with `[i, j]` (ignoring `i`, i.e. just subsetting on `j` = sample:
- subset to `sampleData[j, ]`
- keep only (linked) data elements for the subsetted samples (i.e. data elements linked to other samples not in `j` will be removed from the subsetted object). 
- support re-ordering (`j = c(4, 2, 3)`)
- suport duplication (`j = c(1, 1, 2)`)

This means (last point above) that for `j = c(1, 1)` the Spectra linked with sample one would be duplicated in the `@spectra` slot (i.e. twice the Spectra from sample 1).

Would this type of subsetting be OK with you @lgatto @sgibb ?

**Comment by lgatto** [comment]
I think it makes sense. 

I do have doubts about the duplication of spectra, and would need to think about the implications for different backends, in particular when these are on-disk and writable. Could you describe a use case for this.

**Comment by jorainer** [comment]
For the duplication: I don't have a use case for that yet, it's only that if we provide a `[` method it should allow to perform the same subsetting operations than the *generic* `[`. So, it's more for consistency reasons (and for me to add unit tests).  

In general, backends *should* support that also (this should work out of the box and AFAIK, all backends thus far support it).
