### ISSUE TITLE
Filtering and subsetting of MsExperiment

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/MsExperiment#2]
By supporting different slots with different number of elements subsetting becomes tricky.
`j` in `[i, j, ...]` could be used to subset by sample, but the `i` is tricky. Should this be used to subset by spectra (which is the default for `MSnExp`)? but what with the `@features` and `@chromatograms` slots? how should they then be subsetted?

Or we just allow the use of dedicated filter functions that will be then applied to each slot individually.

@lgatto , any ideas?

**Comment by lgatto** [comment]
That's a good point. 

I don't think we need any `MSnExperiment,[` methods at this stage. I think that, as least in a first instance, these object are more a tool for project management and follow a linear workflow. One could event imagine doing all the spectra data processing using `Spectra` object, and then, once it's done, add it to the `MSnExperiment` object. 

There could probably be functions to create one data type from the other in and `MSnExperiment` object - something like `quantify(myMsExp)` that takes the data from the `Spectra` slot to populate the `Features` slot.
