### ISSUE TITLE
Renaming qfeatures slot?

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/MsExperiment#21]
The [latest commit](https://github.com/rformassspectrometry/MsExperiment/commit/b209bf5455c556968388eeb9b38710d24a8b6608) add supports for `NULL`, `SummarizedExperiment` or `QFeatures` objects for the `qfeatures` slot. 

I am now wondering of `qfeatures` is the best name for that slot. @jorainer, any opinion or suggestion?

**Comment by jorainer** [comment]
hm, that's a good point. maybe `qdata` for *quantitiative data*? I can not think of any better name - so I would also be OK keeping that `qfeatures`.

**Comment by lgatto** [comment]
`@assay` would be a good choice, but it could also be confusing, given that the matrices in a SE are called assays, and the elements in a MultiAssayExperiment/QFeatures objects are also called assays (which themselves can be SEs that contains assays). But may be it is a good name for exactly these reasons?

**Comment by jorainer** [comment]
`@assay` sounds good to me

**Comment by lgatto** [comment]
Done in [this commit](https://github.com/rformassspectrometry/MsExperiment/commit/984106d050b7c9f2b3e3196bd1138a8f401e3633).
