### ISSUE TITLE
Follow renaming of QFeatures ?

### ISSUE THREAD

**Issue by sneumann** [rformassspectrometry/MsExperiment#5]
Hi, the constructor has `Features = "Features"` 
which should probably change to `QFeatures = "QFeatures"`
Yours, Steffen

**Comment by lgatto** [comment]
Indeed, yes. Fixed now.

**Comment by sneumann** [comment]
Hi, I am on it, also requires dependencies etc. Yours, Steffen

**Comment by lgatto** [comment]
I would suggest to discuss any non-trivial changes that you plan to request. There aren't any plans to proceed with the development of this package quite yet.
